### ISSUE TITLE
Any releases?

### ISSUE THREAD

**Issue by Nifty-Neutron** [Maityy/turtle-mod#1]
Hello,
thanks for the mod,
I wanted to test it but there are no builds,
the curseforge page got removed and when I tried to build it my self the build failed(My java knowledge is close to nothing I learnt to build mods but for some reason it didn't work with this).
Thank you,
have a nice day.

**Comment by Maityy** [comment]
Hey. The mod is not ready yet and the final stable release is planned for 1.16.

**Comment by Nifty-Neutron** [comment]
Nice,
I just wanted to help the development and report bugs,
thanks for the response,
have a nice day.

**Comment by Nifty-Neutron** [comment]
Hello again,
I retried building the mod using a github workflow on a fork,
the build fails with this log:

> 2020-05-28T10:21:08.1537708Z ##[group]Run ./gradlew build
> 2020-05-28T10:21:08.1537949Z [36;1m./gradlew build[0m
> 2020-05-28T10:21:08.1583030Z shell: /bin/bash -e {0}
> 2020-05-28T10:21:08.1583164Z env:
> 2020-05-28T10:21:08.1583273Z   JAVA_HOME: /opt/hostedtoolcache/jdk/14.0.1/x64
> 2020-05-28T10:21:08.1583385Z   JAVA_HOME_14.0.1_x64: /opt/hostedtoolcache/jdk/14.0.1/x64
> 2020-05-28T10:21:08.1583481Z ##[endgroup]
> 2020-05-28T10:21:08.2888752Z Downloading https://services.gradle.org/distributions/gradle-6.2.1-bin.zip
> 2020-05-28T10:21:09.9945875Z .............................................................................................
> 2020-05-28T10:21:11.2914656Z 
> 2020-05-28T10:21:11.2915340Z Welcome to Gradle 6.2.1!
> 2020-05-28T10:21:11.2915577Z 
> 2020-05-28T10:21:11.2915805Z Here are the highlights of this release:
> 2020-05-28T10:21:11.2916619Z  - Dependency checksum and signature verification
> 2020-05-28T10:21:11.2921765Z  - Shareable read-only dependency cache
> 2020-05-28T10:21:11.2922314Z  - Documentation links in deprecation messages
> 2020-05-28T10:21:11.2922729Z 
> 2020-05-28T10:21:11.2923309Z For more details see https://docs.gradle.org/6.2.1/release-notes.html
> 2020-05-28T10:21:11.2923601Z 
> 2020-05-28T10:21:11.3686160Z Starting a Gradle Daemon (subsequent builds will be faster)
> 2020-05-28T10:21:15.4747132Z java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
> 2020-05-28T10:21:15.4758650Z 	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
> 2020-05-28T10:21:15.4759171Z 	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
> 2020-05-28T10:21:15.4759481Z 	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
> 2020-05-28T10:21:15.4759722Z 	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
> 2020-05-28T10:21:15.4759963Z 	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
> 2020-05-28T10:21:15.4760227Z 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
> 2020-05-28T10:21:15.4760504Z 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
> 2020-05-28T10:21:15.4760730Z 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
> 2020-05-28T10:21:15.4765947Z 	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
> 2020-05-28T10:21:15.4766319Z 	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
> 2020-05-28T10:21:15.4766562Z 	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
> 2020-05-28T10:21:15.4766827Z 	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
> 2020-05-28T10:21:15.4767070Z 	at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
> 2020-05-28T10:21:15.4767352Z 	at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:49)
> 2020-05-28T10:21:15.4805328Z 	at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
> 2020-05-28T10:21:15.4805523Z 	at org.gradle.internal.instantiation.generator.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:35)
> 2020-05-28T10:21:15.4805675Z 	at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
> 2020-05-28T10:21:15.4805852Z 	at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
> 2020-05-28T10:21:15.4806269Z 	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:64)
> 2020-05-28T10:21:15.4806422Z 	at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
> 2020-05-28T10:21:15.4806578Z 	at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
> 2020-05-28T10:21:15.4806708Z 	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
> 2020-05-28T10:21:15.4806982Z 	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
> 2020-05-28T10:21:15.4807129Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
> 2020-05-28T10:21:15.4807285Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
> 2020-05-28T10:21:15.4807440Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
> 2020-05-28T10:21:15.4807583Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
> 2020-05-28T10:21:15.4807707Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
> 2020-05-28T10:21:15.4807850Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
> 2020-05-28T10:21:15.4807987Z 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
> 2020-05-28T10:21:15.4808128Z 	at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
> 2020-05-28T10:21:15.4808268Z 	at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:105)
> 2020-05-28T10:21:15.4808399Z 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:49)
> 2020-05-28T10:21:15.4808543Z 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
> 2020-05-28T10:21:15.4808696Z 	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
> 2020-05-28T10:21:15.4808857Z 	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:52)
> 2020-05-28T10:21:15.4809011Z 	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
> 2020-05-28T10:21:15.4809150Z 	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
> 2020-05-28T10:21:15.4809281Z 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
> 2020-05-28T10:21:15.4809422Z 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
> 2020-05-28T10:21:15.4809568Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
> 2020-05-28T10:21:15.4809715Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
> 2020-05-28T10:21:15.4809862Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
> 2020-05-28T10:21:15.4810002Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
> 2020-05-28T10:21:15.4810125Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
> 2020-05-28T10:21:15.4810326Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
> 2020-05-28T10:21:15.4810469Z 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> 2020-05-28T10:21:15.4828318Z 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer.prepareSettings(BuildOperatingFiringSettingsPreparer.java:42)
> 2020-05-28T10:21:15.4828673Z 	at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:208)
> 2020-05-28T10:21:15.4844947Z 	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:151)
> 2020-05-28T10:21:15.4845640Z 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
> 2020-05-28T10:21:15.4845774Z 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:120)
> 2020-05-28T10:21:15.4845921Z 	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:74)
> 2020-05-28T10:21:15.4846048Z 	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
> 2020-05-28T10:21:15.4846174Z 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
> 2020-05-28T10:21:15.4846293Z 	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
> 2020-05-28T10:21:15.4846424Z 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
> 2020-05-28T10:21:15.4846553Z 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
> 2020-05-28T10:21:15.4846678Z 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
> 2020-05-28T10:21:15.4848362Z 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 2020-05-28T10:21:15.4848501Z 	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
> 2020-05-28T10:21:15.4848649Z 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
> 2020-05-28T10:21:15.4911813Z 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
> 2020-05-28T10:21:15.4941353Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
> 2020-05-28T10:21:15.4941724Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
> 2020-05-28T10:21:15.4942050Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
> 2020-05-28T10:21:15.4942302Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
> 2020-05-28T10:21:15.4942549Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
> 2020-05-28T10:21:15.4942780Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
> 2020-05-28T10:21:15.4944111Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
> 2020-05-28T10:21:15.4944376Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
> 2020-05-28T10:21:15.4944645Z 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
> 2020-05-28T10:21:15.4944881Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
> 2020-05-28T10:21:15.4945098Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
> 2020-05-28T10:21:15.4953362Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
> 2020-05-28T10:21:15.4953651Z 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:80)
> 2020-05-28T10:21:15.4953888Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
> 2020-05-28T10:21:15.4954116Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
> 2020-05-28T10:21:15.4954343Z 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
> 2020-05-28T10:21:15.4954786Z 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
> 2020-05-28T10:21:15.4955033Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
> 2020-05-28T10:21:15.4955261Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
> 2020-05-28T10:21:15.4955484Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:60)
> 2020-05-28T10:21:15.4956161Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:38)
> 2020-05-28T10:21:15.4957247Z 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
> 2020-05-28T10:21:15.4957661Z 	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
> 2020-05-28T10:21:15.4958118Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
> 2020-05-28T10:21:15.4958359Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
> 2020-05-28T10:21:15.4958609Z 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
> 2020-05-28T10:21:15.4958866Z 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
> 2020-05-28T10:21:15.4959094Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
> 2020-05-28T10:21:15.4959335Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
> 2020-05-28T10:21:15.4959590Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
> 2020-05-28T10:21:15.4959839Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
> 2020-05-28T10:21:15.4960080Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
> 2020-05-28T10:21:15.4960327Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
> 2020-05-28T10:21:15.4960559Z 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
> 2020-05-28T10:21:15.4960884Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
> 2020-05-28T10:21:15.4961109Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4961355Z 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
> 2020-05-28T10:21:15.4961593Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4961834Z 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
> 2020-05-28T10:21:15.4962065Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4962500Z 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
> 2020-05-28T10:21:15.4962750Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4962975Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
> 2020-05-28T10:21:15.4963228Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
> 2020-05-28T10:21:15.4963543Z 	at org.gradle.util.Swapper.swap(Swapper.java:38)
> 2020-05-28T10:21:15.4963770Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
> 2020-05-28T10:21:15.4964008Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4964243Z 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
> 2020-05-28T10:21:15.4964485Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4964697Z 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
> 2020-05-28T10:21:15.4964932Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
> 2020-05-28T10:21:15.4965168Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4965414Z 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
> 2020-05-28T10:21:15.4965652Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
> 2020-05-28T10:21:15.4965886Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
> 2020-05-28T10:21:15.4966108Z 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
> 2020-05-28T10:21:15.4966354Z 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
> 2020-05-28T10:21:15.4966594Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
> 2020-05-28T10:21:15.4966828Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
> 2020-05-28T10:21:15.4967062Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 2020-05-28T10:21:15.4967300Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 2020-05-28T10:21:15.4967532Z 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> 2020-05-28T10:21:15.4967758Z 	at java.base/java.lang.Thread.run(Thread.java:832)
> 2020-05-28T10:21:15.4967914Z 
> 2020-05-28T10:21:15.4968120Z FAILURE: Build failed with an exception.
> 2020-05-28T10:21:15.4968380Z 
> 2020-05-28T10:21:15.4968584Z * What went wrong:
> 2020-05-28T10:21:15.4968781Z Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
> 2020-05-28T10:21:15.4968959Z 
> 2020-05-28T10:21:15.4969164Z * Try:
> 2020-05-28T10:21:15.4970129Z Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 2020-05-28T10:21:15.4970337Z 
> 2020-05-28T10:21:15.4970582Z * Get more help at https://help.gradle.org
> 2020-05-28T10:21:15.4970763Z 
> 2020-05-28T10:21:15.4970934Z BUILD FAILED in 7s
> 2020-05-28T10:21:15.9086454Z ##[error]Process completed with exit code 1.
