### ISSUE TITLE
Compatibiliy with OptiFabric

### ISSUE THREAD

**Issue by Paradoxis** [Maityy/turtle-mod#3]
Hi I was just wondering if this mod is compatible with OptiFabric?
Cheers

**Comment by Nifty-Neutron** [comment]
As far as I know,
The mod is for 1.16 Pre-release 2 at the moment,
and there is no version of OptiFabric for 1.16 nor a version of turtle mod for 1.15.

**Comment by Maityy** [comment]
No, because the mod is only for 1.16+
